version: '3.4'

services:
  whats-app-rest:
    image: whatsapprest:dev
    container_name: whats-app-rest
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "whats-app-rest"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - /Users/chumbimbi/Desktop/Proyectos/AlertaChoco/whats-app-rest:/app
      - /Users/chumbimbi/Desktop/Proyectos/AlertaChoco/whats-app-rest:/src
      - /Users/chumbimbi/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/chumbimbi/.nuget/packages/:/root/.nuget/packages:ro
      - /usr/local/share/dotnet/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/netcoreapp3.1/whats-app-rest.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true